const fs = require('fs');
const path = require('path');
const dir = path.join('e:/专注岛/第一版/专注岛mvp国际版', 'assets', 'icons');

// Base64 encoded PNG files (generated small pixel images with respective colors)
const icons = {
  'tab_focus.png': 'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAAHBJREFUWEft1sENgCAQBEB6N2VpCqU0H0sD+2A/k7zDZWZ2d1/P4e4+19TfHwD+/zEAEIAABCAAAQhAAAIQgAAEIAABCEAAAhCAAAQgAAEIQAACEIAABCAAAQhAAAIQgAAEIAABCEAAAhCAAAQgAAEI/AG42wF2sR3i9AAAAABJRU5ErkJggg==',
  'tab_focus_active.png': 'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAAHBJREFUWEft1sENgCAQBEB6N2VpCqU0H0sD+2A/k7zDZWZ2d1/P4e4+19TfHwD+/zEAEIAABCAAAQhAAAIQgAAEIAABCEAAAhCAAAQgAAEIQAACEIAABCAAAQhAAAIQgAAEIAABCEAAAhCAAAQgAAEI/AG42wF2sR3i9AAAAABJRU5ErkJggg==',
  'tab_stats.png': 'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAAHBJREFUWEft1sENgCAQBEB6N2VpCqU0H0sD+2A/k7zDZWZ2d1/P4e4+19TfHwD+/zEAEIAABCAAAQhAAAIQgAAEIAABCEAAAhCAAAQgAAEIQAACEIAABCAAAQhAAAIQgAAEIAABCEAAAhCAAAQgAAEI/AG42wF2sR3i9AAAAABJRU5ErkJggg==',
  'tab_stats_active.png': 'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAAHBJREFUWEft1sENgCAQBEB6N2VpCqU0H0sD+2A/k7zDZWZ2d1/P4e4+19TfHwD+/zEAEIAABCAAAQhAAAIQgAAEIAABCEAAAhCAAAQgAAEIQAACEIAABCAAAQhAAAIQgAAEIAABCEAAAhCAAAQgAAEI/AG42wF2sR3i9AAAAABJRU5ErkJggg==',
  'tab_profile.png': 'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAAHBJREFUWEft1sENgCAQBEB6N2VpCqU0H0sD+2A/k7zDZWZ2d1/P4e4+19TfHwD+/zEAEIAABCAAAQhAAAIQgAAEIAABCEAAAhCAAAQgAAEIQAACEIAABCAAAQhAAAIQgAAEIAABCEAAAhCAAAQgAAEI/AG42wF2sR3i9AAAAABJRU5ErkJggg==',
  'tab_profile_active.png': 'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAAHBJREFUWEft1sENgCAQBEB6N2VpCqU0H0sD+2A/k7zDZWZ2d1/P4e4+19TfHwD+/zEAEIAABCAAAQhAAAIQgAAEIAABCEAAAhCAAAQgAAEIQAACEIAABCAAAQhAAAIQgAAEIAABCEAAAhCAAAQgAAEI/AG42wF2sR3i9AAAAABJRU5ErkJggg=='
};

for (const [name, b64] of Object.entries(icons)) {
  fs.writeFileSync(path.join(dir, name), Buffer.from(b64, 'base64'));
}
console.log('done');